services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: open5gs
    ports:
      - "27017:27017"
    networks:
      mongonet:
        ipv4_address: 10.20.20.30
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
       mongonet:
        ipv4_address: 10.20.20.20
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/admin
      ME_CONFIG_BASICAUTH: "false"

  open5gs:
    build:
      context: ./open5gs
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      ran: ### para colocar o USERSIMUE
        ipv4_address: 192.168.98.10
      mongonet:
        ipv4_address: 10.20.20.10
    container_name: open5gs
    ports:
      - "8805:8805"
      - "2123:2123"
      - "60673:60673"
      - "7777:7777"
      - "5868:5868"
      - "44513:44513"
      - "9090:9090"




volumes:
  mongo_data:


networks:
  mongonet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24

  ran:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.98.0/24